### ISSUE TITLE
metadata_url is incorrect

### ISSUE THREAD

**Issue by Sergong** [Azure-Samples/virtual-machines-python-scheduled-events-central-logging#4]
with the metadata_url set to "http://169.254.169.254/metadata/scheduledevents?api-version=2017-03-01" the following error occurs:

 2017-04-19 19:01:06,191 [DEBUG] Azure Scheduled Events Interactive Tool
 2017-04-19 19:01:06,191 [DEBUG] get_scheduled_events was called
Traceback (most recent call last):
  File "scheduledEventsInteractiveTool.py", line 126, in <module>
    main()
  File "scheduledEventsInteractiveTool.py", line 121, in main
    data=get_scheduled_events()
  File "scheduledEventsInteractiveTool.py", line 75, in get_scheduled_events
    resp=urllib.request.urlopen(req)
  File "C:\Users\local-admin\AppData\Local\Programs\Python\Python35-32\lib\urlli
b\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\local-admin\AppData\Local\Programs\Python\Python35-32\lib\urlli
b\request.py", line 472, in open
    response = meth(req, response)
  File "C:\Users\local-admin\AppData\Local\Programs\Python\Python35-32\lib\urlli
b\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\local-admin\AppData\Local\Programs\Python\Python35-32\lib\urlli
b\request.py", line 510, in error
    return self._call_chain(*args)
  File "C:\Users\local-admin\AppData\Local\Programs\Python\Python35-32\lib\urlli
b\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\local-admin\AppData\Local\Programs\Python\Python35-32\lib\urlli
b\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

**Comment by zivraf** [comment]
We are in the middle of switching to a new URL (the one used in the sample).
During this transition you can use the old URL instead:
http://169.254.169.254/metadata/latest/scheduledevents
We will continue supporting the old URL (the one with /latest/) until the GA date.
