### ISSUE TITLE
IOTHub or Event Hub??

### ISSUE THREAD

**Issue by Sergong** [Azure-Samples/virtual-machines-python-scheduled-events-central-logging#7]
The instructions refer to setting up an IOTHub and refer to using a connection string but there is no clear guidance on whether endpoints are required. Setting a custom Endpoint for an IOTHub does require setting up an Eventhub with a namespace as well. If you try to use the connection string displayed for iothubownwer on your IOTHub Shared Access Policies, this shows a Hostname= instead of an Endpoint= and does not work. You'll get the following error using that connection string:

2017-04-20 11:53:28,982 [DEBUG] Azure Scheduled Events Interactive Tool
2017-04-20 11:53:28,982 [DEBUG] get_scheduled_events was called
2017-04-20 11:53:28,998 [INFO] handle_scheduled_events was called with 0 events
Traceback (most recent call last):
  File "scheduledEventsInteractiveTool.py", line 148, in <module>
    main()
  File "scheduledEventsInteractiveTool.py", line 145, in main
    handle_scheduled_events(data)
  File "scheduledEventsInteractiveTool.py", line 122, in handle_scheduled_events
    send_to_event_hub(eventHubMessage)
  File "scheduledEventsInteractiveTool.py", line 78, in send_to_event_hub
    result = ehMsgSender.sendD2CMsg(messageAsJson)
  File "scheduledEventsInteractiveTool.py", line 70, in sendD2CMsg
    with urllib.request.urlopen(req) as f:
  File "C:\Users\local-admin\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\local-admin\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\Users\local-admin\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\local-admin\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "C:\Users\local-admin\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\local-admin\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: 40103: Invalid authorization token signature

This is your first hint that you do need to create an Eventhub and associated namespace, which you can then subsequently use to create a custom endpoint for your IOTHub. You will then need to use the connection string displayed for the RootManageSharedAccessKey under Shared Access Policies the for EventHub rather than the connection string for iothubowner under Shared Access Policies for your IOTHub. 
Only then does it all work! So the documentation can benefit from a bit more detail around what is required for the setup of the IOThub.

Thanks!

**Comment by EliPinkertonMicrosoft** [comment]
Thanks for the detailed feedback @Sergong! Indeed, the EventHub intro documentation would likely be a better starting place, as that's what's primarily used in the sample.

I've created a [PR](https://github.com/Azure-Samples/virtual-machines-python-scheduled-events-central-logging/pull/8) taking these changes into account, removing the mention of the IoT Hub entirely. Feedback on clarity/detail would be appreciated!
